from PyQt6 import QtCore, QtGui, QtWidgets

class CurrencyConverterView(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Currency_Converter")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Convert Currency From
        self.verticalLayout_Currency_From = QtWidgets.QVBoxLayout()
        self.verticalLayout_Currency_From.setObjectName("verticalLayout_Currency_From")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_From.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_From.addItem(spacerItem1)
        self.lineEdit_Currency_From = QtWidgets.QLineEdit(parent=self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Currency_From.sizePolicy().hasHeightForWidth())
        self.lineEdit_Currency_From.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(20)
        self.lineEdit_Currency_From.setFont(font)
        self.lineEdit_Currency_From.setObjectName("lineEdit_Currency_From")
        self.verticalLayout_Currency_From.addWidget(self.lineEdit_Currency_From)
        self.comboBox_Currency_From = QtWidgets.QComboBox(parent=self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Currency_From.sizePolicy().hasHeightForWidth())
        self.comboBox_Currency_From.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TF2 Build")
        font.setPointSize(16)
        self.comboBox_Currency_From.setFont(font)
        self.comboBox_Currency_From.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_Currency_From.setObjectName("comboBox_Currency_From")
        self.comboBox_Currency_From.addItem("")
        self.comboBox_Currency_From.addItem("")
        self.comboBox_Currency_From.addItem("")
        self.verticalLayout_Currency_From.addWidget(self.comboBox_Currency_From)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_From.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_From.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_Currency_From)

        # Convert Currency To
        self.verticalLayout_Currency_To = QtWidgets.QVBoxLayout()
        self.verticalLayout_Currency_To.setObjectName("verticalLayout_Currency_To")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_To.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_To.addItem(spacerItem5)
        self.lineEdit_Currency_To = QtWidgets.QLineEdit(parent=self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Currency_To.sizePolicy().hasHeightForWidth())
        self.lineEdit_Currency_To.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TF2 Secondary")
        font.setPointSize(20)
        self.lineEdit_Currency_To.setFont(font)
        self.lineEdit_Currency_To.setObjectName("lineEdit_Currency_To")
        self.verticalLayout_Currency_To.addWidget(self.lineEdit_Currency_To)
        self.comboBox_Currency_To = QtWidgets.QComboBox(parent=self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Currency_To.sizePolicy().hasHeightForWidth())
        self.comboBox_Currency_To.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TF2 Build")
        font.setPointSize(16)
        self.comboBox_Currency_To.setFont(font)
        self.comboBox_Currency_To.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_Currency_To.setObjectName("comboBox_Currency_To")
        self.comboBox_Currency_To.addItem("")
        self.comboBox_Currency_To.addItem("")
        self.comboBox_Currency_To.addItem("")
        self.verticalLayout_Currency_To.addWidget(self.comboBox_Currency_To)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_To.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Currency_To.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_Currency_To)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_Currency_From.setToolTip(_translate("Form", "Convert From"))
        self.comboBox_Currency_From.setPlaceholderText(_translate("Form", "Convert From"))
        self.comboBox_Currency_From.setItemText(0, _translate("Form", "USD"))
        self.comboBox_Currency_From.setItemText(1, _translate("Form", "PND"))
        self.comboBox_Currency_From.setItemText(2, _translate("Form", "INR"))
        self.comboBox_Currency_To.setToolTip(_translate("Form", "Convert To"))
        self.comboBox_Currency_To.setPlaceholderText(_translate("Form", "Convert To"))
        self.comboBox_Currency_To.setItemText(0, _translate("Form", "INR"))
        self.comboBox_Currency_To.setItemText(1, _translate("Form", "PKR"))
        self.comboBox_Currency_To.setItemText(2, _translate("Form", "RUB"))
